cart/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.cart, name='cart'),
    re_path(r'(?P<id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'(?P<slug>[\w-]+)/$', views.add_to_cart, name='add_to_cart'),
]

djangoecommerce/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.homepage, name='home'),
    re_path(r'^products/', include('products.urls')),
    re_path(r'cart/', include('cart.urls')),
    re_path(r'^contact/', include('contact.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'products'

urlpatterns = [
    re_path(r'^$', views.productsList, name='list'),
    re_path(r'^s/$', views.search, name='search'),
    re_path(r'^sale/$', views.productsSale, name='sale'),
    re_path(r'^(?P<cat>[\w-]+)/$', views.category, name='category'),
    re_path(r'^(?P<cat>[\w-]+)/(?P<subcat>[\w-]+)/$', views.subCategory, name='subCategory'),
    re_path(r'^(?P<cat>[\w-]+)/(?P<subcat>[\w-]+)/(?P<slug>[\w-]+)/$', views.productDetail, name='details'),
]

products/models.py
from django.db import models
import os
from datetime import datetime

# Create your models here.

def get_upload_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{instance.product.slug}-{instance.id}-image.{ext}'
    return os.path.join(
        '%s' % instance.product.slug, filename
    )

def get_upload_path_thumb(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{instance.slug}-{instance.id}-thumbnail.{ext}'
    return os.path.join(
        '%s' % instance.slug, 'thumbnail', filename
    )

class Category(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    parent = models.ForeignKey('Category', null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['title']
        unique_together = ('slug', 'parent', 'title')
        verbose_name = 'CATEGORY'
        verbose_name_plural = 'Categories'

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' -> '.join(full_path[::-1])

class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    category = models.ForeignKey(Category, blank=True, null=True, related_name='Category', on_delete=models.DO_NOTHING)
    #category = models.ManyToManyField(Category, blank=True, null=True, related_name='Category')
    price = models.DecimalField(decimal_places=2, max_digits=20)
    sale = models.DecimalField(decimal_places=2, max_digits=20, null=True, blank=True)
    slug = models.SlugField(unique=True)
    thumbnail = models.ImageField(upload_to=get_upload_path_thumb, default='doggo.png')
    date = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-update']
        unique_together = ('title', 'slug')
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    # def get_cat_list(self):
    #     k = self.category
    #
    #     breadcrumb = ["masno"]
    #     while k is not None:
    #         breadcrumb.append(k.slug)
    #         k = k.parent
    #     for i in range(len(breadcrumb) - 1):
    #         breadcrumb[i] = ' x '.join(breadcrumb[-1:i - 1:-1])
    #     return breadcrumb[-1:0:-1]

class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name = 'image')
    #thumbnail = models.ImageField(upload_to='media/products/')
    image = models.ImageField(upload_to=get_upload_path, default='media/products/szlugson.jpg')

    class Meta:
        verbose_name = 'ADDITIONAL IMAGE'
        verbose_name_plural = 'ADDITIONAL IMAGES'

class VariationManager(models.Manager):
    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size')
    def shoe_sizes(self):
        return super(VariationManager, self).filter(variation_category='shoe_size')
    def skate_sizes(self):
        return super(VariationManager, self).filter(variation_category='skate_size')

VAR_CATEGORIES = {
    ('size', 'size'),
    ('shoe_size', 'shoe_size'),
    ('skate_size', 'skate_size')
}

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='universal')
    title = models.CharField(max_length=120, blank=True)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

    objects = VariationManager()

    class Meta:
        ordering = ['product']

    def __str__(self):
        return self.title



products/views.py
from django.shortcuts import render
from .models import Product, Category, ProductImages
from django.db.models import Q
from django.http import Http404
import random
# Create your views here.

def productsList(request):
    try:
        products = Product.objects.all()
        #category = Category.objects.all()
        #categorylol = Category.objects.filter(title__in=['clothing', 'skate', 'shoes'])
        category = Category.objects.filter(parent__exact=None)
        category_list = list(category)
        sub_category = Category.objects.filter(parent__in=category_list)
        #print(sub_category)
    except:
        #products = None
        raise Http404
    template = 'products/products.html'
    context = {
        'products': products,
        'category': category,
        'sub_category': sub_category,
               }
    return render(request, template, context)
    #     mainCategory = Category.objects.select_related().filter(title = cat)
    #     allCategories = Category.objects.all()
    #     products = Product.objects.all()
    #     template = 'products/products.html'
    #     context = {
    #         'mainCategory': mainCategory,
    #         'allCategories': allCategories,
    #         'products': products,
    #     }
    #     return render(request, template, context)
    # except cat.DoesNotExists:
    #     return productDetail(request, cat)

def productsSale(request):
    try:
        products = Product.objects.all()
        #category = Category.objects.all()
        #categorylol = Category.objects.filter(title__in=['clothing', 'skate', 'shoes'])
        category = Category.objects.filter(parent__exact=None)
        category_list = list(category)
        sub_category = Category.objects.filter(parent__in=category_list)
        #print(sub_category)
    except:
        #products = None
        raise Http404
    template = 'products/sale.html'
    context = {
        'products': products,
        'category': category,
        'sub_category': sub_category,
               }
    return render(request, template, context)

def category(request, cat):
    #print(subCategories)
    try:
        #products = Category.objects.select_related().get(title=cat)
        #products = Category.objects.select_related().get(title=cat).product_set.all()
        products = Product.objects.filter(category__parent__title=cat)
        subCategories = Category.objects.get(title=cat).category_set.all()
    except:
        #products = None
        #subCategories = None
        raise Http404
    template = 'products/category.html'
    context = {
        'products': products,
        'category': cat,
        'subCategories': subCategories
    }
    #print(products)
    return render(request, template, context)

def subCategory(request, cat, subcat):
    try:
        products = Product.objects.filter(category__title=subcat)
        subCategories = Category.objects.get(title=cat).category_set.all()
        #check = Category.objects.filter(title=subcat)
        if not Category.objects.filter(title=subcat).exists():
            raise Http404
    except:
        #products = None
        #subCategories = None
        raise Http404
    template = 'products/category.html'
    context = {
        'products': products,
        'category': cat,
        'subCategory': subcat,
        'subCategories': subCategories,
    }
    print(products)
    #print(subcat)
    #print(subCategories)
    #print(check)
    return render(request, template, context)

def productDetail(request, cat, subcat, slug):
    try:
        products = Product.objects.get(slug=slug)
        # random_products = Product.objects.filter(category__title=subcat)
        products_id_list = list(Product.objects.filter(category__title=subcat).values_list('id', flat=True))
        random_products_id_list = random.sample(products_id_list, min(len(products_id_list), 3))
        random_products = Product.objects.filter(id__in=random_products_id_list)
        # random_products_id_list = random.sample(cat_products_id_list, min(len(cat_products_id_list), 3))
        product_image = ProductImages.objects.filter(product__slug=slug)
    except:
        #products = None
        raise Http404
    template = 'products/productsDetail.html'
    context = {
        'p': products,
        'cat': cat,
        'subcat': subcat,
        'slug': slug,
        'random_products': random_products,
        'product_image': product_image,
        'subcat_s': subcat[:len(subcat)-1],
    }
    return render(request, template, context)

def search(request):
    try:
        s = request.GET['search']
    except:
        s = None
        # raise Http404
    if s:
        products = Product.objects.filter(Q(title__icontains=s) | Q(category__title=s))
    else:
        products = None
    template = 'search/search.html'
    context = {
        'query': s,
        'products': products,
    }
    return render(request, template, context)
    #print(s)

templates/products/category.html
{% extends 'template.html' %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static '/products/products-style.css' %}">
<title> {{ category.title }} - sk8shop</title>
{% endblock %}


{% block content %}
<section class="banner">
    <figure><img src="{% static '/products/images/background.jpg' %}"></figure>
</section>
<div class="line"></div>
<aside>
    <a href="{% url 'products:category' cat=category.title.lower %}">{{ category.title }}</a>
    <ul>
        {% for sub in subCategories %}
        <li><a href="{% url 'products:subCategory' cat=sub.parent.title subcat=sub.title %}">{{sub.title}}</a></li>
        {% endfor %}
    </ul>
</aside>
<div class="pipe"></div>
<main>
    {% for p in products %}
    <div class="category-product">
        <figure><img src="{{ p.thumbnail.url }}" alt="image.png"></figure>
        <a
            href="{% url 'products:details' cat=p.category.parent.title subcat=p.category.title slug=p.slug %}">{{p.title}}</a>
        {% if p.sale %}
        <p><s>${{p.price}}</s> ${{p.sale}}</p>
        {% else %}
        <p>${{p.price}}</p>
        {% endif %}
    </div>
    {% endfor %}
</main>
{% endblock %}

templates/products/products.html
{% extends 'template.html' %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static '/products/products-style.css' %}">
<title> products - sk8shop</title>
{% endblock %}

{% block content %}
<section class="banner">
    <figure><img src="{% static '/products/images/background.jpg' %}"></figure>
</section>
<div class="line"></div>
<aside>
    <h1>PRODUCTS</h1>
    <ul>
        {% for c in category %}
        <li><a href="{% url 'products:category' cat=c.title.lower %}">{{c.title}}</a>
            <ul>
                {% for sub in sub_category %}
                {% if c.title in sub.parent.title %}
                <li><a href="{% url 'products:subCategory' cat=c.title.lower subcat=sub.title %}">{{sub.title}}</a></li>
                {% endif %}
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
</aside>
<div class="pipe"></div>
<main>
    {% for p in products %}
    <div class="category-product">
        <figure><img src="{{ p.thumbnail.url }}" alt="image.png"></figure>
        <a
            href="{% url 'products:details' cat=p.category.parent.title subcat=p.category.title slug=p.slug %}">{{p.title}}</a>
        {% if p.sale %}
        <p><s>${{p.price}}</s> ${{p.sale}}</p>
        {% else %}
        <p>${{p.price}}</p>
        {% endif %}
    </div>
    {% endfor %}
</main>
{% endblock %}

templates/products/productsDetail.html
{% extends 'template.html' %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static '/products/product-detail.css' %}">
<script src="{% static '/products/script.js' %}"></script>
<title>{{ p.title }} - sk8shop</title>
{% endblock %}

{% block content %}
<main>
    <section class="single-product-images">
        <section class="breadcrumbs">
            <a href="{% url 'home' %}">Home</a>
            <span class="breadcrumbs-divider">/</span>
            <a href="{% url 'products:list' %}">Products</a>
            <span class="breadcrumbs-divider">/</span>
            <a href="{% url 'products:category' cat=p.category.parent.title %}">{{p.category.parent.title}}</a>
            <span class="breadcrumbs-divider">/</span>
            <a href="{% url 'products:subCategory' cat=p.category.parent.title subcat=p.category.title %}">{{p.category.title}}</a>
        </section>
        <section class="images">
            <div>
                {% for i in product_image %}
                <figure class="single-product-image"><img src="{{ i.image.url }}" alt="image.png" onclick="foo(this)">
                </figure>
                {% endfor %}
            </div>
            <figure class="single-product-thumbnail"><img src="{{ p.thumbnail.url }}" id="main-image" alt="image.png">
            </figure>
        </section>
    </section>
    <section class="single-product-text">
        <h2>{{ p.title }}</h2>
        <div class="line"></div>
        {% if p.sale %}
        <h3><s>${{ p.price }}</s> ${{ p.sale }}</h3>
        {% else %}
        <h3>${{ p.price }}</h3>
        {% endif %}
        {% if p.variation_set.all %}
        <form method="GET" action="{% url 'add_to_cart' slug=p.slug %}" class="variation" id="variation">
            {% if p.variation_set.sizes %}
            <small class="bold">{{subcat_s}} SIZE</small>
            {% for item in p.variation_set.sizes %}
            <input type="radio" name="size" value="{{ item.title }}" class="form-radio" id="size-{{item.title}}">
            <label for="size-{{item.title}}" class="label-radio">{{ item.title }}</label>
            {% endfor %}
            <small class="bold">QUANTITY</small>
            <input type="number" value="1" name="qty" min="1" max="10" class="QUANTITY">
            {% elif p.variation_set.shoe_sizes %}
            <small class="bold">{{subcat_s}} SIZE</small>
            {% for item in p.variation_set.shoe_sizes %}
            <input type="radio" name="shoe_size" value="{{ item.title }}" class="form-radio"
                id="shoe_size-{{item.title}}">
            <label for="shoe_size-{{item.title}}" class="label-radio">{{ item.title }}</label>
            {% endfor %}
            <small class="bold">QUANTITY</small>
            <input type="number" value="1" name="qty" min="1" max="10" class="QUANTITY">
            </select>
            {% elif p.variation_set.skate_sizes %}
            <small class="bold">{{subcat_s}} SIZE</small>
            {% for item in p.variation_set.skate_sizes %}
            <input type="radio" name="skate_size" value="{{ item.title }}" class="form-radio"
                id="skate_sizes-{{item.title}}">
            <label for="skate_sizes-{{item.title}}" class="label-radio">{{ item.title }}</label>
            {% endfor %}
            <small class="bold">QUANTITY</small>
            <input type="number" value="1" name="qty" min="1" max="10" class="QUANTITY">
            {% else %}
            <input type="radio" name="size" value="UNIVERSAL" class="form-radio" id="size-UNIVERSAL">
            <label for="size-UNIVERSAL" class="label-radio">UNIVERSAL</label>
            <small class="bold">QUANTITY</small>
            <input type="number" value="1" name="qty" min="1" max="10" class="QUANTITY">
            {% endif %}
            <a href="#" onclick='document.forms["variation"].submit(); return false;'">ADD TO CART</a>
        </form>
        {% endif %}
        <p class="bold">DESCRIPTION:</p>
                <p>{{ p.description }}</p>
                <div class="line"></div>
                <ul>
                    <li><a href="#"><img src="{% static '/template/images/twitter.png' %}"></a></li>
                    <li><a href="#"><img src="{% static '/template/images/facebook.png' %}"></a></li>
                    <li><a href="#" class="social-footer-icons"><img
                                src="{% static '/template/images/youtube.png' %}"></a></li>
                    <li><a href="#" class="social-footer-icons"><img
                                src="{% static '/template/images/instagram.png' %}"></a>
                    </li>
                </ul>
    </section>
</main>
<aside>
    <div class="line"></div>
    <h2>YOU MAY ALSO LIKE</h2>
    {% for x in random_products %}
    <div class="aside-products">
        <figure><img src="{{ x.thumbnail.url }}" alt="image.png"></figure>
        <a
            href="{% url 'products:details' cat=x.category.parent.title subcat=x.category.title slug=x.slug %}">{{ x.title }}</a>
        {% if x.sale %}
        <p><s>${{x.price}}</s> ${{x.sale}}</p>
        {% else %}
        <p>${{x.price}}</p>
        {% endif %}
    </div>
    {% endfor %}
</aside>
{% endblock %}

templates/products/sale.html
{% extends 'template.html' %}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static '/products/products-style.css' %}">
<title> sale - sk8shop</title>
{% endblock %}

{% block content %}
<section class="banner">
    <figure><img src="{% static '/products/images/background.jpg' %}"></figure>
</section>
<div class="line"></div>
<aside>
    <h1>PRODUCTS</h1>
    <ul>
        {% for c in category %}
        <li><a href="{% url 'products:category' cat=c.title.lower %}">{{c.title}}</a>
            <ul>
                {% for sub in sub_category %}
                {% if c.title in sub.parent.title %}
                <li><a href="{% url 'products:subCategory' cat=c.title.lower subcat=sub.title %}">{{sub.title}}</a></li>
                {% endif %}
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
</aside>
<div class="pipe"></div>
<main>
    {% for p in products %}
    {% if p.sale %}
    <div class="category-product">
        <figure><img src="{{ p.thumbnail.url }}" alt="image.png"></figure>
        <a
            href="{% url 'products:details' cat=p.category.parent.title subcat=p.category.title slug=p.slug %}">{{p.title}}</a>
        {% if p.sale %}
        <p><s>${{p.price}}</s> ${{p.sale}}</p>
        {% else %}
        <p>${{p.price}}</p>
        {% endif %}
    </div>
    {% endif %}
    {% endfor %}
</main>
{% endblock %}